#!/usr/bin/env node
/**
 * Guard: property 1's mechanical test, given a referent.
 *
 * CLAUDE.md says **"a change that adds capability should not touch the kernel"**. Until
 * `packages/eagent` was deleted that sentence had no referent in this package — the Layout
 * block assigned the word "kernel" to the other one, and `grep -ani kernel packages/core/src/`
 * still returns exactly one hit, about the OS kernel. So the test could be quoted but never run.
 *
 * The one running P1 gate, `check-surface.mjs`, pins the exported NAME SET. That is the right
 * pin for the public contract and the wrong one for this: it reported
 * `surface guard ok: … unchanged` on the day `run/engine.ts` crossed 6,100 lines, having grown
 * from 1,375 in 21 days across 28 of this branch's 69 `feat` commits. Name-set stability and
 * kernel stability are different properties and only one of them was observed.
 *
 * ── What this pins ──────────────────────────────────────────────────────────────
 *
 * A FILE LIST — `scripts/kernel.json` — plus, for each file, a written reason it is kernel.
 * Not a line count: EAgent pinned a kernel line count, the ceiling had to be raised four times,
 * and it taxed correct primitives as much as incidental ones (`check-surface.mjs` argues this
 * at length; the argument is not repeated here). Not a content digest either — that was the
 * closest analogue of `surface.json` and it was rejected, because the reviewed diff would be one
 * opaque line, `"a3f9…" → "b12c…"`, and a pin whose update teaches a reviewer nothing is a
 * rubber stamp. `surface.json` works because a name-set diff is legible.
 *
 * ── How it decides a change "adds capability" ────────────────────────────────────
 *
 * It reads git. A commit whose subject is `feat(...)` / `feat!:` and which touches a pinned file
 * must carry a `Kernel-seam:` trailer naming the seam that was missing. `fix`, `docs`, `refactor`,
 * `test`, `chore` are free to touch the kernel — fixing the kernel is what a kernel is for; P1
 * constrains capability, not maintenance.
 *
 * Reading git is awkward for a guard and it is the honest choice: nothing in the TREE records
 * intent, and intent is the entire predicate. What that CANNOT catch, exhaustively:
 *
 *   - a capability landed under `fix:`, `refactor:` or `chore:`. The convention IS the signal;
 *     a mislabelled commit defeats it and no tree-reading check would have caught it either.
 *   - a squash-merge that collapses a `feat` into a subject of some other type. Merge commits
 *     are skipped outright (`--no-merges`): `git show --name-only` reports nothing for them.
 *   - capability added OUTSIDE the list that makes the kernel harder to change later.
 *   - uncommitted work. A dirty kernel file has no commit message yet, so it is reported as a
 *     NOTICE and never as a failure — otherwise nobody could edit the kernel and run the gate.
 *
 * ── The escape hatch, and why it is not a rubber stamp ───────────────────────────
 *
 * `Kernel-seam:` in the commit body. It cannot be regenerated by a command the way a `--write`
 * pin can; it costs a sentence of design argument; and it is permanent and greppable, so
 * `git log --grep='^Kernel-seam:'` is the P1 debt census — a number nobody can quietly reset.
 *
 * ── Failing closed ───────────────────────────────────────────────────────────────
 *
 * No git, an unreadable pin, an EMPTY pin, a file listed with no `why`, or a pinned path that is
 * no longer in the tree are all exit 1. The last matters most: `check-surface.mjs`'s own history
 * is a guard reading a stale artifact and printing "ok", and a pin that silently stops observing
 * is the same failure. An empty `files` list is refused for the same reason — it would pass
 * everything while watching nothing.
 *
 * ── What this does NOT establish ─────────────────────────────────────────────────
 *
 * Nothing about whether `run/engine.ts` should be split. The audit did not check that, and
 * `engine.ts:1-24` gives three real structural arguments for co-location. Making the boundary
 * observable is the goal here; the number this guard produces is the input to that argument,
 * not its conclusion.
 *
 * Usage: `node scripts/check-kernel.mjs [root]` — root defaults to the repo containing this
 * script. It is an argument so the guard can be pointed at a fixture and shown to fail;
 * `packages/core/test/kernel-boundary.test.ts` does exactly that.
 */

import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = fileURLToPath(new URL("../", import.meta.url));
const root = resolve(process.argv[2] ?? REPO);
const PIN = join(root, "scripts", "kernel.json");

/** Every refusal exits here, so there is exactly one way for this guard to say no. */
function refuse(...lines) {
  console.error("kernel guard FAILED — " + lines[0]);
  for (const l of lines.slice(1)) console.error(l);
  process.exit(1);
}

function git(...args) {
  const r = gitRaw(...args);
  return { ...r, out: r.out.trim() };
}

/**
 * Untrimmed, because `status --porcelain` puts its two status columns in the first two
 * characters and an unmodified-in-index file leads with a SPACE. Trimming the whole output
 * ate that space on the first line only, and the notice printed `ackages/core/...`.
 */
function gitRaw(...args) {
  const r = spawnSync("git", ["-C", root, ...args], { encoding: "utf8" });
  return { ok: r.status === 0, out: r.stdout ?? "", err: (r.stderr ?? "").trim() };
}

// ── the pin ──────────────────────────────────────────────────────────────────────

if (!existsSync(PIN)) refuse(`${PIN} not found. The kernel has no referent without it.`);

let pin;
try {
  pin = JSON.parse(readFileSync(PIN, "utf8"));
} catch (e) {
  refuse(`${PIN} is not valid JSON: ${e.message}`);
}

if (!Array.isArray(pin.files) || pin.files.length === 0) {
  refuse(
    "the pinned kernel is empty.",
    "  A list of zero files passes every commit while observing nothing, which is",
    "  indistinguishable from having no guard. If the kernel really is empty, delete",
    "  this guard and the claim in CLAUDE.md together.",
  );
}

const paths = [];
for (const entry of pin.files) {
  if (typeof entry?.path !== "string" || entry.path.length === 0) {
    refuse(`${PIN}: every \`files\` entry needs a \`path\`; got ${JSON.stringify(entry)}`);
  }
  if (typeof entry?.why !== "string" || entry.why.trim().length === 0) {
    refuse(
      `${PIN}: \`${entry.path}\` is pinned with no \`why\`.`,
      "  A list nobody can justify is worse than no list — it converts a design claim into",
      "  a habit. Say which non-negotiable this file makes true, or drop it from the list.",
    );
  }
  if (!existsSync(join(root, entry.path))) {
    refuse(
      `\`${entry.path}\` is pinned as kernel but is not in the tree.`,
      "  Renamed, moved or deleted. A pin that points at nothing keeps printing ok while",
      "  observing nothing — update `files` in the same commit that moved the file.",
    );
  }
  paths.push(entry.path);
}

if (typeof pin.since !== "string" || pin.since.trim().length === 0) {
  refuse(`${PIN}: \`since\` must name the commit at which the kernel became observable.`);
}

/**
 * An OBJECT NAME, never a ref. Reproduced while writing this guard: with `"since": "HEAD"` the
 * range `HEAD..HEAD` is empty, so the guard printed `kernel guard ok: … 0 commits since fb813ec`
 * over a `feat` commit that had just rewritten a pinned file. Any moving ref — `HEAD`, `@`, a
 * branch, a tag someone re-points — is the same vacuum, and it is the cheapest way to switch
 * this guard off without deleting it.
 */
if (!/^[0-9a-f]{7,40}$/.test(pin.since.trim())) {
  refuse(
    `${PIN}: \`since\` must be a commit SHA, not \`${pin.since}\`.`,
    "  A ref moves with the branch, and `HEAD..HEAD` is empty — the guard would print ok",
    "  over any commit at all. Pin the object name of the commit being grandfathered.",
  );
}

// ── git ──────────────────────────────────────────────────────────────────────────

if (!git("rev-parse", "--git-dir").ok) {
  refuse(
    `${root} is not a git repository.`,
    "  Intent lives in commit messages and nowhere else, so with no history this guard",
    "  cannot decide. It refuses rather than passing: loosening is never the default.",
  );
}

const since = git("rev-parse", "--verify", "--quiet", `${pin.since}^{commit}`);
if (!since.ok) {
  refuse(
    `\`since\` (${pin.since}) is not a commit in this repository.`,
    "  A rewritten or shallow history leaves the guard unable to name the range it should",
    "  judge. Re-pin `since` to a commit this checkout actually has.",
  );
}

const RS = "\x1e";
const US = "\x1f";
const log = git(
  "log",
  "--no-merges",
  "--format=%H%x1f%s%x1f%b%x1e",
  `${since.out}..HEAD`,
);
if (!log.ok) refuse(`could not read \`${pin.since}..HEAD\`: ${log.err}`);

const commits = log.out
  .split(RS)
  .map((c) => c.trim())
  .filter(Boolean)
  .map((c) => {
    const [sha, subject, body = ""] = c.split(US);
    return { sha, subject, body };
  });

/** The repo's convention is Conventional Commits; only `feat` claims to add capability. */
const FEAT = /^feat(\([^)]*\))?!?:/;
const SEAM = /^Kernel-seam:[ \t]*(\S.*)$/m;

const violations = [];
const declared = [];

for (const c of commits) {
  if (!FEAT.test(c.subject)) continue;
  const shown = git("show", "--name-only", "--format=", c.sha);
  if (!shown.ok) refuse(`could not read the file list of ${c.sha}: ${shown.err}`);
  const touched = shown.out.split("\n").filter((f) => paths.includes(f.trim()));
  if (touched.length === 0) continue;
  const seam = SEAM.exec(c.body);
  if (seam) declared.push({ ...c, touched, seam: seam[1].trim() });
  else violations.push({ ...c, touched });
}

// ── the working tree: a notice, never a failure ──────────────────────────────────

const dirty = gitRaw("status", "--porcelain", "--", ...paths);
const dirtyFiles = dirty.ok
  ? dirty.out
      .split("\n")
      .filter((l) => l.length > 3)
      .map((l) => l.slice(3).trim())
  : [];

// ── report ───────────────────────────────────────────────────────────────────────

if (violations.length > 0) {
  console.error("kernel guard FAILED — a change that adds capability touched the kernel.");
  console.error("");
  for (const v of violations) {
    console.error(`  ${v.sha.slice(0, 7)}  ${v.subject}`);
    for (const f of v.touched) console.error(`            ${f}`);
  }
  console.error("");
  console.error("CLAUDE.md property 1: if a feature must change the kernel, the kernel is missing");
  console.error("a seam, and the seam is the thing to design. Three ways forward, all deliberate:");
  console.error("");
  console.error("  1. Move the capability behind a seam so the kernel file stops changing.");
  console.error("  2. If it genuinely belongs in the kernel, amend the commit with a trailer");
  console.error("     naming the seam that was missing:");
  console.error("");
  console.error("         Kernel-seam: <which seam was absent, and why adding one was worse>");
  console.error("");
  console.error("     It is not a rubber stamp: `git log --grep='^Kernel-seam:'` is the running");
  console.error("     census of every time the kernel absorbed a feature.");
  console.error("");
  console.error(`  3. Or the file is not kernel after all — argue that in ${PIN}.`);
  process.exit(1);
}

console.log(
  `kernel guard ok: ${paths.length} files pinned, ` +
    `${commits.length} commits since ${since.out.slice(0, 7)}, ` +
    `${declared.length} declared seam${declared.length === 1 ? "" : "s"}`,
);
for (const d of declared) {
  console.log(`  seam  ${d.sha.slice(0, 7)}  ${d.subject}`);
  console.log(`        ${d.seam}`);
}
if (dirtyFiles.length > 0) {
  console.log(
    `  notice: ${dirtyFiles.length} kernel file(s) modified but not committed — ` +
      "no commit message yet, so not judged:",
  );
  for (const f of dirtyFiles) console.log(`        ${f}`);
}
process.exit(0);
